// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"blog/app/article/rpc/internal/logic"
	"blog/app/article/rpc/internal/svc"
	"blog/app/article/rpc/pb/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) PageList(ctx context.Context, in *rpc.SearchReq) (*rpc.PageData, error) {
	l := logic.NewPageListLogic(ctx, s.svcCtx)
	return l.PageList(in)
}

func (s *RpcServer) CategoryList(ctx context.Context, in *rpc.EmptyReq) (*rpc.CategoryRes, error) {
	l := logic.NewCategoryListLogic(ctx, s.svcCtx)
	return l.CategoryList(in)
}

func (s *RpcServer) Info(ctx context.Context, in *rpc.InfoReq) (*rpc.Article, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}

func (s *RpcServer) Push(ctx context.Context, in *rpc.UpdateReq) (*rpc.EmptyRes, error) {
	l := logic.NewPushLogic(ctx, s.svcCtx)
	return l.Push(in)
}

func (s *RpcServer) Upload(ctx context.Context, in *rpc.UploadReq) (*rpc.UploadRes, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *RpcServer) Delete(ctx context.Context, in *rpc.DeleteReq) (*rpc.EmptyRes, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
