// Code generated by goctl. DO NOT EDIT.
// Source: uuid.proto

package server

import (
	"context"

	"blog/app/uuid/internal/logic/uuidservice"
	"blog/app/uuid/internal/svc"
	"blog/app/uuid/pb/rpc"
)

type UuidServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedUuidServiceServer
}

func NewUuidServiceServer(svcCtx *svc.ServiceContext) *UuidServiceServer {
	return &UuidServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UuidServiceServer) GenUuid(ctx context.Context, in *rpc.GenUuidReq) (*rpc.GenUuidRes, error) {
	l := uuidservicelogic.NewGenUuidLogic(ctx, s.svcCtx)
	return l.GenUuid(in)
}
