// Code generated by goctl. DO NOT EDIT.
package types

type AdminDeleteReq struct {
	Id  int64   `json:"id"`  //单删
	Ids []int64 `json:"ids"` //批量删除
}

type AdminInfo struct {
	Id       int64     `json:"id"`
	Name     string    `json:"name"`
	Phone    string    `json:"phone"`
	RoleId   int       `json:"role_id"`
	RoleInfo AdminRole `json:"role_info"`
}

type AdminInfoReq struct {
	Id int `form:"id"`
}

type AdminPageList struct {
	Total    int64       `json:"total"`
	Data     []AdminInfo `json:"data"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
}

type AdminPermission struct {
	Id        int64   `json:"id"`
	MenuId    int32   `json:"menu_id"`
	Uri       string  `json:"uri"`
	Menu      []int32 `json:"menu"`
	CreatedAt string  `json:"created_at"`
}

type AdminPermissionDeleteReq struct {
	Id  int64   `json:"id"`  //单删
	Ids []int64 `json:"ids"` //批量删除
}

type AdminPermissionInfoReq struct {
	Id int `form:"id"`
}

type AdminPermissionUpdateReq struct {
	Id     int64  `json:"id"`
	MenuId int32  `json:"menu_id" validate:"required" label:"请选择关联菜单"`
	Uri    string `json:"uri" validate:"required" label:"请填写接口权限"`
}

type AdminRole struct {
	Id         int     `json:"id"`
	Name       string  `json:"name"`
	Permission []int32 `json:"permission"`
}

type AdminRoleDeleteReq struct {
	Id  int64   `json:"id"`  //单删
	Ids []int64 `json:"ids"` //批量删除
}

type AdminRoleInfoReq struct {
	Id int `form:"id"`
}

type AdminRolePageList struct {
	Total    int64       `json:"total"`
	Data     []AdminRole `json:"data"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
}

type AdminRoleSearchReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	Keyword  string `form:"keyword"`
}

type AdminRoleUpdateReq struct {
	Id         int64   `json:"id"`
	Name       string  `json:"name" validate:"required" label:"角色名称"`
	Permission []int32 `json:"permission" validate:"required" label:"拥有权限"`
}

type AdminSearchReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	Keyword  string `form:"keyword"`
}

type AdminUpdateReq struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"  validate:"required" label:"账号"`
	Password string `json:"password" validate:"required" label:"密码"`
	Phone    string `json:"phone" validate:"required" label:"手机号"`
	RoleId   int32  `json:"role_id" validate:"required" label:"角色"`
}

type Article struct {
	Uuid       string        `json:"uuid"`
	CategoryId int32         `json:"categroy_id"`
	Title      int64         `json:"title"`
	Cover      string        `json:"cover"`
	UserUuid   string        `json:"user_uuid"`
	LikeNum    int64         `json:"like_num"`
	ViewNum    int64         `json:"view_num"`
	Status     int32         `json:"status"`
	DetailInfo ArticleDetail `json:"detail_info"`
}

type ArticleCategroy struct {
	Id       int64  `json:"id"`
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name"`
	Children []ArticleCategroy
}

type ArticleCategroyDeleteReq struct {
	Id  int64   `json:"id"`  //单删
	Ids []int64 `json:"ids"` //批量删除
}

type ArticleCategroyInfoReq struct {
	Id int64 `form:"id"`
}

type ArticleCategroyUpdateReq struct {
	Id       int64  `json:"id"`
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name"`
	Weight   int32  `json:"weight"`
}

type ArticleDeleteReq struct {
	Uuid  int64    `json:"uuid"`  //单删
	Uuids []string `json:"uuids"` //批量删除
}

type ArticleDetail struct {
	ArticleUuid string `json:"article_uuid"`
	Content     string `json:"content"`
	Reason      string `json:"reason"`
}

type ArticleInfoReq struct {
	Uuid int64 `form:"uuid"`
}

type ArticlePageList struct {
	Total    int64     `json:"total"`
	Data     []Article `json:"data"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
}

type ArticleSearchReq struct {
	Page     int    `form:"page"`
	PageSize int    `form:"page_size"`
	Keyword  string `form:"keyword"`
}

type ArticleUpdateReq struct {
	Id         int64  `json:"id"`
	CategoryId int32  `json:"categroy_id"`
	Title      int64  `json:"title"`
	Cover      string `json:"cover"`
	Content    string `json:"content"`
}

type EnvRes struct {
	Env        string `json:"env"`
	Uid        string `json:"uid"`
	TimeZone   string `json:"timezone"`
	Timestamps int    `json:"timestamps"`
	Agent      string `json:"agent"`
	Ip         string `json:"ip"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required" label:"账号"`
	Password string `json:"password" validate:"required" label:"密码"`
}

type LoginRes struct {
	Token        string    `json:"token"`
	RefreshToken string    `json:"refresh_token"`
	AdminInfo    AdminInfo `json:"admin_info"`
}

type Menu struct {
	Id         int64           `json:"id"`
	ParentId   int64           `json:"parent_id"`
	Name       string          `json:"name"`
	Uri        string          `json:"uri"`
	Icon       string          `json:"icon"`
	Weight     int32           `json:"weight"`
	Children   []Menu          `json:"children"`
	Permission AdminPermission `json:"permission"`
}

type MenuDeleteReq struct {
	Id  int64   `json:"id"`  //单删
	Ids []int64 `json:"ids"` //批量删除
}

type MenuInfoReq struct {
	Id int `form:"id"`
}

type MenuUpdateReq struct {
	Id       int64  `json:"id"`
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name" validate:"required" label:"菜单名称"`
	Uri      string `json:"uri"`
	Icon     string `json:"icon"`
	Weight   int32  `json:"weight"`
}
