// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"blog/app/article/rpc/internal/logic/commonservice"
	"blog/app/article/rpc/internal/svc"
	"blog/app/article/rpc/pb/rpc"
)

type CommonServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedCommonServiceServer
}

func NewCommonServiceServer(svcCtx *svc.ServiceContext) *CommonServiceServer {
	return &CommonServiceServer{
		svcCtx: svcCtx,
	}
}

// 公共文章
func (s *CommonServiceServer) PageList(ctx context.Context, in *rpc.SearchReq) (*rpc.PageData, error) {
	l := commonservicelogic.NewPageListLogic(ctx, s.svcCtx)
	return l.PageList(in)
}

func (s *CommonServiceServer) CategoryList(ctx context.Context, in *rpc.EmptyReq) (*rpc.CategoryRes, error) {
	l := commonservicelogic.NewCategoryListLogic(ctx, s.svcCtx)
	return l.CategoryList(in)
}

func (s *CommonServiceServer) Info(ctx context.Context, in *rpc.InfoReq) (*rpc.Article, error) {
	l := commonservicelogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
