// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: verify.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VerifyService_GenToken_FullMethodName    = "/verify.VerifyService/GenToken"
	VerifyService_RemoveToken_FullMethodName = "/verify.VerifyService/RemoveToken"
	VerifyService_Auth_FullMethodName        = "/verify.VerifyService/Auth"
)

// VerifyServiceClient is the client API for VerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifyServiceClient interface {
	GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error)
	RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*EmptyRes, error)
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error)
}

type verifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyServiceClient(cc grpc.ClientConnInterface) VerifyServiceClient {
	return &verifyServiceClient{cc}
}

func (c *verifyServiceClient) GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error) {
	out := new(GenTokenRes)
	err := c.cc.Invoke(ctx, VerifyService_GenToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifyServiceClient) RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, VerifyService_RemoveToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifyServiceClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error) {
	out := new(AuthRes)
	err := c.cc.Invoke(ctx, VerifyService_Auth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyServiceServer is the server API for VerifyService service.
// All implementations must embed UnimplementedVerifyServiceServer
// for forward compatibility
type VerifyServiceServer interface {
	GenToken(context.Context, *GenTokenReq) (*GenTokenRes, error)
	RemoveToken(context.Context, *RemoveTokenReq) (*EmptyRes, error)
	Auth(context.Context, *AuthReq) (*AuthRes, error)
	mustEmbedUnimplementedVerifyServiceServer()
}

// UnimplementedVerifyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVerifyServiceServer struct {
}

func (UnimplementedVerifyServiceServer) GenToken(context.Context, *GenTokenReq) (*GenTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenToken not implemented")
}
func (UnimplementedVerifyServiceServer) RemoveToken(context.Context, *RemoveTokenReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveToken not implemented")
}
func (UnimplementedVerifyServiceServer) Auth(context.Context, *AuthReq) (*AuthRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedVerifyServiceServer) mustEmbedUnimplementedVerifyServiceServer() {}

// UnsafeVerifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyServiceServer will
// result in compilation errors.
type UnsafeVerifyServiceServer interface {
	mustEmbedUnimplementedVerifyServiceServer()
}

func RegisterVerifyServiceServer(s grpc.ServiceRegistrar, srv VerifyServiceServer) {
	s.RegisterService(&VerifyService_ServiceDesc, srv)
}

func _VerifyService_GenToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServiceServer).GenToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyService_GenToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServiceServer).GenToken(ctx, req.(*GenTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifyService_RemoveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServiceServer).RemoveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyService_RemoveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServiceServer).RemoveToken(ctx, req.(*RemoveTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifyService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifyService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServiceServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifyService_ServiceDesc is the grpc.ServiceDesc for VerifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verify.VerifyService",
	HandlerType: (*VerifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenToken",
			Handler:    _VerifyService_GenToken_Handler,
		},
		{
			MethodName: "RemoveToken",
			Handler:    _VerifyService_RemoveToken_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _VerifyService_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verify.proto",
}
