// Code generated by goctl. DO NOT EDIT.
// Source: verify.proto

package server

import (
	"context"

	"blog/app/verify/rpc/internal/logic"
	"blog/app/verify/rpc/internal/svc"
	"blog/app/verify/rpc/pb/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) GenToken(ctx context.Context, in *rpc.GenTokenReq) (*rpc.GenTokenRes, error) {
	l := logic.NewGenTokenLogic(ctx, s.svcCtx)
	return l.GenToken(in)
}

func (s *RpcServer) RemoveToken(ctx context.Context, in *rpc.RemoveTokenReq) (*rpc.RemoveTokenRes, error) {
	l := logic.NewRemoveTokenLogic(ctx, s.svcCtx)
	return l.RemoveToken(in)
}

func (s *RpcServer) Auth(ctx context.Context, in *rpc.AuthReq) (*rpc.AuthRes, error) {
	l := logic.NewAuthLogic(ctx, s.svcCtx)
	return l.Auth(in)
}
