// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package userservice

import (
	"context"

	"blog/app/article/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article     = rpc.Article
	Category    = rpc.Category
	CategoryRes = rpc.CategoryRes
	DeleteReq   = rpc.DeleteReq
	Detail      = rpc.Detail
	EmptyReq    = rpc.EmptyReq
	EmptyRes    = rpc.EmptyRes
	ExamineReq  = rpc.ExamineReq
	InfoReq     = rpc.InfoReq
	PageData    = rpc.PageData
	SearchReq   = rpc.SearchReq
	UpdateReq   = rpc.UpdateReq
	UploadReq   = rpc.UploadReq
	UploadRes   = rpc.UploadRes
	User        = rpc.User

	UserService interface {
		// 个人文章
		PageList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*PageData, error)
		Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Article, error)
		Push(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*EmptyRes, error)
		Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadRes, error)
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*EmptyRes, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 个人文章
func (m *defaultUserService) PageList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*PageData, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.PageList(ctx, in, opts...)
}

func (m *defaultUserService) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Article, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}

func (m *defaultUserService) Push(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.Push(ctx, in, opts...)
}

func (m *defaultUserService) Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadRes, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.Upload(ctx, in, opts...)
}

func (m *defaultUserService) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	client := rpc.NewUserServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
