// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"blog/app/user/rpc/internal/logic"
	"blog/app/user/rpc/internal/svc"
	"blog/app/user/rpc/pb/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Register(ctx context.Context, in *rpc.RegisterReq) (*rpc.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *RpcServer) Login(ctx context.Context, in *rpc.LoginReq) (*rpc.LoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *RpcServer) Info(ctx context.Context, in *rpc.InfoReq) (*rpc.User, error) {
	l := logic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
