// Code generated by goctl. DO NOT EDIT.
// Source: verify.proto

package verifyservice

import (
	"context"

	"blog/app/verify/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthReq        = rpc.AuthReq
	AuthRes        = rpc.AuthRes
	EmptyRes       = rpc.EmptyRes
	GenTokenReq    = rpc.GenTokenReq
	GenTokenRes    = rpc.GenTokenRes
	JwtMap         = rpc.JwtMap
	RemoveTokenReq = rpc.RemoveTokenReq

	VerifyService interface {
		GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error)
		RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*EmptyRes, error)
		Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error)
	}

	defaultVerifyService struct {
		cli zrpc.Client
	}
)

func NewVerifyService(cli zrpc.Client) VerifyService {
	return &defaultVerifyService{
		cli: cli,
	}
}

func (m *defaultVerifyService) GenToken(ctx context.Context, in *GenTokenReq, opts ...grpc.CallOption) (*GenTokenRes, error) {
	client := rpc.NewVerifyServiceClient(m.cli.Conn())
	return client.GenToken(ctx, in, opts...)
}

func (m *defaultVerifyService) RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	client := rpc.NewVerifyServiceClient(m.cli.Conn())
	return client.RemoveToken(ctx, in, opts...)
}

func (m *defaultVerifyService) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*AuthRes, error) {
	client := rpc.NewVerifyServiceClient(m.cli.Conn())
	return client.Auth(ctx, in, opts...)
}
