// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Uuid         string        `json:"uuid"`
	Title        string        `json:"title"`
	Cover        string        `json:"cover"`
	CategoryId   int32         `json:"category_id"`
	CategoryInfo Category      `json:"category_info"`
	DetailInfo   ArticleDetail `json:"detail_info"`
}

type ArticleDetail struct {
	Content string `json:"content"`
}

type ArticleInfoReq struct {
	Uuid string `form:"uuid"`
}

type ArticlePageList struct {
	Total    int64     `json:"total"`
	Data     []Article `json:"data"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
}

type ArticleSearchReq struct {
	Page       int    `json:"page"`
	PageSize   int    `json:"page_size"`
	CategoryId int32  `json:"category_id"`
	Keyword    string `json:"category_id"`
}

type Category struct {
	Id       int64  `json:"id"`
	ParentId int32  `json:"parent_id"`
	Name     string `json:"name"`
}
