// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"blog/app/article/rpc/internal/logic/adminservice"
	"blog/app/article/rpc/internal/svc"
	"blog/app/article/rpc/pb/rpc"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

// 管理后台
func (s *AdminServiceServer) PageList(ctx context.Context, in *rpc.SearchReq) (*rpc.PageData, error) {
	l := adminservicelogic.NewPageListLogic(ctx, s.svcCtx)
	return l.PageList(in)
}

func (s *AdminServiceServer) Delete(ctx context.Context, in *rpc.DeleteReq) (*rpc.EmptyRes, error) {
	l := adminservicelogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *AdminServiceServer) Examine(ctx context.Context, in *rpc.DeleteReq) (*rpc.EmptyRes, error) {
	l := adminservicelogic.NewExamineLogic(ctx, s.svcCtx)
	return l.Examine(in)
}
