// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v1article "blog/app/article/api/internal/handler/v1/article"
	v1category "blog/app/article/api/internal/handler/v1/category"
	"blog/app/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/article/info",
					Handler: v1article.InfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/v1/article/page_list",
					Handler: v1article.PageListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/v1/category/all_list",
					Handler: v1category.AllListHandler(serverCtx),
				},
			}...,
		),
	)
}
