// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v1category "blog/app/article/api/internal/handler/v1/category"
	v1common "blog/app/article/api/internal/handler/v1/common"
	v1user "blog/app/article/api/internal/handler/v1/user"
	"blog/app/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					// 分类列表
					Method:  http.MethodGet,
					Path:    "/v1/category/all_list",
					Handler: v1category.AllListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					// 文章详情
					Method:  http.MethodGet,
					Path:    "/v1/common/info",
					Handler: v1common.InfoHandler(serverCtx),
				},
				{
					// 分页列表
					Method:  http.MethodGet,
					Path:    "/v1/common/page_list",
					Handler: v1common.PageListHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.UserAuthMiddleware},
			[]rest.Route{
				{
					// 删除
					Method:  http.MethodPost,
					Path:    "/v1/user/delete",
					Handler: v1user.DeleteHandler(serverCtx),
				},
				{
					// 我发布的
					Method:  http.MethodGet,
					Path:    "/v1/user/page_list",
					Handler: v1user.PageListHandler(serverCtx),
				},
				{
					// 发布文章
					Method:  http.MethodPost,
					Path:    "/v1/user/push",
					Handler: v1user.PushHandler(serverCtx),
				},
				{
					// 上传文件
					Method:  http.MethodPost,
					Path:    "/v1/user/upload",
					Handler: v1user.UploadHandler(serverCtx),
				},
			}...,
		),
	)
}
