// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package server

import (
	"context"

	"blog/app/article/rpc/internal/logic/admin"
	"blog/app/article/rpc/internal/svc"
	"blog/app/article/rpc/pb/rpc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// 管理后台
func (s *AdminServer) PageList(ctx context.Context, in *rpc.SearchReq) (*rpc.PageData, error) {
	l := adminlogic.NewPageListLogic(ctx, s.svcCtx)
	return l.PageList(in)
}

func (s *AdminServer) Delete(ctx context.Context, in *rpc.DeleteReq) (*rpc.EmptyRes, error) {
	l := adminlogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *AdminServer) Examine(ctx context.Context, in *rpc.DeleteReq) (*rpc.EmptyRes, error) {
	l := adminlogic.NewExamineLogic(ctx, s.svcCtx)
	return l.Examine(in)
}
