// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package rpcClient

import (
	"context"

	"blog/app/article/rpc/pb/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Article     = rpc.Article
	Category    = rpc.Category
	CategoryRes = rpc.CategoryRes
	DeleteReq   = rpc.DeleteReq
	Detail      = rpc.Detail
	EmptyReq    = rpc.EmptyReq
	EmptyRes    = rpc.EmptyRes
	InfoReq     = rpc.InfoReq
	PageData    = rpc.PageData
	SearchReq   = rpc.SearchReq
	UpdateReq   = rpc.UpdateReq
	UploadReq   = rpc.UploadReq
	UploadRes   = rpc.UploadRes
	User        = rpc.User

	Rpc interface {
		PageList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*PageData, error)
		CategoryList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*CategoryRes, error)
		Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Article, error)
		Push(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*EmptyRes, error)
		Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadRes, error)
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*EmptyRes, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) PageList(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*PageData, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.PageList(ctx, in, opts...)
}

func (m *defaultRpc) CategoryList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*CategoryRes, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.CategoryList(ctx, in, opts...)
}

func (m *defaultRpc) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Article, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}

func (m *defaultRpc) Push(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Push(ctx, in, opts...)
}

func (m *defaultRpc) Upload(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadRes, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Upload(ctx, in, opts...)
}

func (m *defaultRpc) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
