// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Phone    int64  `json:"phone" validate:"required" label:"手机号"`
	Password string `json:"password" validate:"required" label:"密码"`
}

type LoginRes struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	User         User   `json:"user"`
}

type RegisterReq struct {
	Nickname string `json:"nickname" validate:"required" label:"昵称"`
	Phone    int64  `json:"phone" validate:"required" label:"手机号"`
	Password string `json:"password" validate:"required" label:"密码"`
}

type User struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Phone    int64  `json:"phone"`
}

type UserInfoReq struct {
	Id int64 `form:"id"`
}
