// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: uuid.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UuidService_GenUuid_FullMethodName = "/uuid.UuidService/GenUuid"
)

// UuidServiceClient is the client API for UuidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UuidServiceClient interface {
	GenUuid(ctx context.Context, in *GenUuidReq, opts ...grpc.CallOption) (*GenUuidRes, error)
}

type uuidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUuidServiceClient(cc grpc.ClientConnInterface) UuidServiceClient {
	return &uuidServiceClient{cc}
}

func (c *uuidServiceClient) GenUuid(ctx context.Context, in *GenUuidReq, opts ...grpc.CallOption) (*GenUuidRes, error) {
	out := new(GenUuidRes)
	err := c.cc.Invoke(ctx, UuidService_GenUuid_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UuidServiceServer is the server API for UuidService service.
// All implementations must embed UnimplementedUuidServiceServer
// for forward compatibility
type UuidServiceServer interface {
	GenUuid(context.Context, *GenUuidReq) (*GenUuidRes, error)
	mustEmbedUnimplementedUuidServiceServer()
}

// UnimplementedUuidServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUuidServiceServer struct {
}

func (UnimplementedUuidServiceServer) GenUuid(context.Context, *GenUuidReq) (*GenUuidRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenUuid not implemented")
}
func (UnimplementedUuidServiceServer) mustEmbedUnimplementedUuidServiceServer() {}

// UnsafeUuidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UuidServiceServer will
// result in compilation errors.
type UnsafeUuidServiceServer interface {
	mustEmbedUnimplementedUuidServiceServer()
}

func RegisterUuidServiceServer(s grpc.ServiceRegistrar, srv UuidServiceServer) {
	s.RegisterService(&UuidService_ServiceDesc, srv)
}

func _UuidService_GenUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenUuidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UuidServiceServer).GenUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UuidService_GenUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UuidServiceServer).GenUuid(ctx, req.(*GenUuidReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UuidService_ServiceDesc is the grpc.ServiceDesc for UuidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UuidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uuid.UuidService",
	HandlerType: (*UuidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenUuid",
			Handler:    _UuidService_GenUuid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uuid.proto",
}
