// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: uuid.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenUuidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 业务模块
	BizType string `protobuf:"bytes,1,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
}

func (x *GenUuidReq) Reset() {
	*x = GenUuidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uuid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUuidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUuidReq) ProtoMessage() {}

func (x *GenUuidReq) ProtoReflect() protoreflect.Message {
	mi := &file_uuid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUuidReq.ProtoReflect.Descriptor instead.
func (*GenUuidReq) Descriptor() ([]byte, []int) {
	return file_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *GenUuidReq) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

type GenUuidRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 服务模块
	BizType string `protobuf:"bytes,1,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	// 唯一标识
	BizId string `protobuf:"bytes,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
}

func (x *GenUuidRes) Reset() {
	*x = GenUuidRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uuid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUuidRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUuidRes) ProtoMessage() {}

func (x *GenUuidRes) ProtoReflect() protoreflect.Message {
	mi := &file_uuid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUuidRes.ProtoReflect.Descriptor instead.
func (*GenUuidRes) Descriptor() ([]byte, []int) {
	return file_uuid_proto_rawDescGZIP(), []int{1}
}

func (x *GenUuidRes) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *GenUuidRes) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

var File_uuid_proto protoreflect.FileDescriptor

var file_uuid_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x22, 0x27, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x7a, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3e, 0x0a, 0x0a, 0x47,
	0x65, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x7a,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x7a,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x69, 0x7a, 0x49, 0x64, 0x32, 0x3c, 0x0a, 0x0b, 0x55,
	0x75, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65,
	0x6e, 0x55, 0x75, 0x69, 0x64, 0x12, 0x10, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x47, 0x65, 0x6e,
	0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x47,
	0x65, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uuid_proto_rawDescOnce sync.Once
	file_uuid_proto_rawDescData = file_uuid_proto_rawDesc
)

func file_uuid_proto_rawDescGZIP() []byte {
	file_uuid_proto_rawDescOnce.Do(func() {
		file_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_uuid_proto_rawDescData)
	})
	return file_uuid_proto_rawDescData
}

var file_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uuid_proto_goTypes = []interface{}{
	(*GenUuidReq)(nil), // 0: uuid.GenUuidReq
	(*GenUuidRes)(nil), // 1: uuid.GenUuidRes
}
var file_uuid_proto_depIdxs = []int32{
	0, // 0: uuid.UuidService.GenUuid:input_type -> uuid.GenUuidReq
	1, // 1: uuid.UuidService.GenUuid:output_type -> uuid.GenUuidRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uuid_proto_init() }
func file_uuid_proto_init() {
	if File_uuid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uuid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUuidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uuid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUuidRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uuid_proto_goTypes,
		DependencyIndexes: file_uuid_proto_depIdxs,
		MessageInfos:      file_uuid_proto_msgTypes,
	}.Build()
	File_uuid_proto = out.File
	file_uuid_proto_rawDesc = nil
	file_uuid_proto_goTypes = nil
	file_uuid_proto_depIdxs = nil
}
